baseurl = "https://postrausch.tech"
title = "Postrausch"
theme = "hugo-coder"
languagecode = "de"
defaultcontentlanguage = "de"

pagenate = 20

[markup]
[markup.tableOfContents]
startLevel = 3
endLevel = 5
[markup.highlight]
style = "github-dark"
[markup.goldmark.renderer]
      unsafe = true

[params]
  author = "Henry Rausch"
  info = "Fachinformatiker für Systemintegration"
  description = "Automatisiere die Zukunft!"
  keywords = "blog,developer,persona, Systemintegrator, Cloud"
  avatarurl = "/media/matrix-pb.png"

  impressum = "/impressum"
  datenschutz = "/datenschutz"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"
  touchIcon = "/img/apple-touch-icon.png"

  since = 2021

  enableTwemoji = true

  colorScheme = "dark"
  hidecolorschemetoggle = true

  # Series see also post count
  maxSeeAlsoItems = 3

  [taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

  # Social links
  [[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/HRA42/"

  # Menu links
  [[menu.main]]
  name = "Blog"
  weight = 1
  url  = "https://blog.postrausch.tech" 
  [[menu.main]]
  name = "neuer Blog (Info)"
  weight = 1
  url  = "posts/newblog" 
  [[menu.main]]
  name = "Über mich"
  weight = 2
  url = "about/"

# Privacy
[privacy]
      [privacy.disqus]
            disable = true
      [privacy.youtube]
            privacyEnhanced = true
            relatedVideos = false
      [privacy.googleAnalytics]
            disable = true
      [privacy.instagram]
            simple = true
      [privacy.twitter]
            enableDNT = true
            simple = true
      [privacy.vimeo]
            enableDNT = true
            simple = true
